# Generated by Django 3.1 on 2021-01-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=30)),
                ('To', models.CharField(max_length=30)),
                ('Amount', models.IntegerField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Person',
            new_name='Customers',
        ),
    ]
