# Generated by Django 3.1 on 2021-01-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0005_auto_20210110_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Current_Balance',
            field=models.BigIntegerField(max_length=100000000000),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='Amount',
            field=models.BigIntegerField(max_length=100000000000),
        ),
    ]
